### ISSUE TITLE
Did not reach the speed mentioned in the paper to 30 frames per second

### ISSUE THREAD

**Issue by zlgybz** [xaldyz/dataflow-orbslam#3]
Hi, Your job is great！
I tried your project on TX2. The 00 sequence of the KITTI data set is used. The average time for each frame is 0.117s. Did not reach the speed mentioned in the paper to 30 frames per second。And the original ORBSLAM2 took an average  time of 0.107s. 
I used the tool to check the GPU usage when running your project. But GPU usage rate is very low. Did I miss any steps? Why does this happen？

**Comment by xaldyz** [comment]
Hello,
sorry for the late reply, and thanks for the compliment!

Yeah, if GPU is not used, that means there is some tweak to be made on the CMake configuration. If you look through the option by using [ccmake](https://linux.die.net/man/1/ccmake) command, you will see there are 2 options which need to be modified:

- `USE_CUSTOM_VX`, by default set to FALSE
- `USE_PIPELINE`, by default set to FALSE

The first one enables the GPU acceleration, which is good enough for the KITTI dataset, but to further push performance, the second flag controls the possibility to pipeline multiple frames. By combining both of them, you should be able to achieve the 30 FPS mark.
Remember to run jetson_clocks, otherwise you will have very bizarre results due the DVFS technology.

I'll keep this open for a week or two, if nothing newer comes up then I'll proceed to close it

**Comment by zlgybz** [comment]
Thanks for your reply. But after I changed USE_CUSTOM_VX to TRUE,  the error message occurred after  running:
Error calling pthread_setaffinity_np:22
Error calling pthread_setaffinity_np:22
Segmentation fault(core dumped)

**Comment by xaldyz** [comment]
About the `pthread_setaffinity_np` error, this is because software assumes 6 cores available, which you can obtain by running the command `sudo nvpmodel -m 0`
I don't remember right away the source of the segmentation fault, but I recall to have seen that. Since due the COVID situation, I have difficulty to reach the board where the code is, so I cannot directly inspect this.
Can you give me more insights on where it is happening? I believe it could be after the initialization in `src/System.cc`, or in the constructor of `src/ORBExtractor.cc`.

**Comment by zlgybz** [comment]
Thanks for your reply. The terminal output is as follows：
Camera Parameters: 
- fx: 718.856
- fy: 718.856
- cx: 607.193
- cy: 185.216
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 10
- color order: RGB (ignored if grayscale)
Init: 0x0, 2000 features!
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
Global optimum selection
Creating thread 1
Creating thread 2
Creating thread 3
Creating thread 4
Creating thread 5
Init: 0x0, 4000 features!
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
-19 -- -19
Global optimum selection
Creating thread 1
Creating thread 2
Creating thread 3
Creating thread 4
Creating thread 5

ORB Extractor Parameters: 
- Number of Features: 2000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

-------
Start processing sequence ...
Images in the sequence: 1022

Segmentation fault (core dumped)

**Comment by xaldyz** [comment]
@zlgybz sorry for the late reply, I kept thinking about what kind of problem you could have since I downloaded from this repo into a clean TX2 environment and I got zero issues.
Then it hit me: you mentioned you got the 00 sequence, so I presume you run it with the "KITTI00-02.yaml" settings file.
This file missed two important parameters which are needed for the GPU part to function correctly, and an example is found in the [KITTI04-12.yaml](https://github.com/xaldyz/dataflow-orbslam/blob/2429b96e1961d291fe40cb4c4bbcfa77bc7f11be/Examples/Monocular/KITTI04-12.yaml#L21-L23) setting file.
Try to set those two parameters with the correct width and height of the images, and everything should run accordingly

**Comment by seomk97** [comment]
Hi,
Can you give more detail about the metric "The percentage of reconstructed map"?
Is there any ground truth 3D feature point map in KITTI?
Thank you for great job

**Comment by xaldyz** [comment]
> Hi,
> Can you give more detail about the metric "The percentage of reconstructed map"?
> Is there any ground truth 3D feature point map in KITTI?
> Thank you for great job

Hi @seomk97 ,
the percentage of reconstructed map is exactly how it sound: how much of the map the algorithm was able to reconstruct using the specific board, in our case the Jetson TX2.
We noted that, even if average speed was good, some computational spikes took a little bit more time (for example when there is a loop check). This happened to make the system lose the localisation point, so only partial map is available since the system is not able to generate more points. The losing point was quite consistent across different runs, so we decided to put the metric available for future works.
About KITTI, there is the 3D trajectory available [at their site](http://www.cvlibs.net/datasets/kitti/eval_odometry.php) with the code to calculate the difference with the trajectory you provide!

I ask you to open a new issue if the question is not related to the original one, to avoid divergence 😉

**Comment by seomk97** [comment]
@xaldyz Thanks for your reply! I understood your explanation partially. I couldn't find ground truth 3D map in KITTI datasets. How can you measure the percentage of reconstructed map of your algorithm exactly? I mean where is 100% constructed map?
(I should have opened a new issue, really sorry about that)
