### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by seomk97** [xaldyz/dataflow-orbslam#4]
Hi, Thank you sharing great job.
I have several questions about the paper.

1. Where can I get the 100% constructed map of KITTI for calculate the percentage of reconstructed map?
(Should I run the ORB-SLAM2 once without any time constraint so that the algorithm fully constructs the map of each key frame? Is it deterministic?)

2. In the DAG of feature extraction block, only three yellow nodes are GPU/CPU implementation. any reason of this?
(Do you have any profile data of performance of each implementation?)

Many thanks!

**Comment by xaldyz** [comment]
Hello @seomk97 
for point 1 you find all the informations [in the page of KITTI](http://www.cvlibs.net/datasets/kitti/eval_odometry.php), and specifically the one that states "Download odometry ground truth poses (4 MB)", which you have to register to get the download link. Once you downloaded that file, you find the ground truth for every frame in the first 10 or 11 sequences. The other ones are kept secret for challenge purpose.
About the determinism of ORB-SLAM, no, it is not deterministic by design, since there is parallelism between the Tracking part and the Mapping part. We tried to sequentialise them, but results weren't always the same, albeit close to each other. Probably there is something left uninitialized somewhere, and the random initialization gives different results.
Remember the map, at least in our semantic, is the pose of the agent (position + orientation) at every frame, not the reconstruction of the surrounding.

About point 2, the reason about only 3 nodes were both CPU and GPU is because it was a preliminary implementation, and we used what OpenCV had already available to process on GPU. This work focused on re-arranging available implementations that we were aware of. You can of course make the GPU version of the other nodes too, but then you have to make sure to use the underline hardware resource in a smart way.
This means it is not always the best choice to put everything in the fastest accelerator, because it can produce idle times in other acceleration. For more on this topic, we published a work that may help you on what you are working on: [On the Task Mapping and Scheduling for DAG-based Embedded Vision Applications on Heterogeneous Multi/Many-core Architectures](https://ieeexplore.ieee.org/document/9116462A).
I don't have the numbers available for each implementation, but (VERY) roughly, the speedup are like this (all decreases when the image is smaller)
- Scale 2-3x
- FAST 10-15x (watch out, times are data-dependant!)
- Gaussian 5x
- A preliminary GPU ORB version we made is about 1.7x
You have to add copy times between CPU and GPU, which are small but not zero, and increase the bus traffic (and energy consumption too).

I hope I gave you some enlightenment you were looking for, if you have more questions feel free to share!

**Comment by seomk97** [comment]
Hi @xaldyz 
I am very grateful for your considerate reply
and the work you mentioned are very helpful for me
I think I might have few questions and bring them here soon
Many thanks!
